### ISSUE TITLE
Draft rules for tweet contents

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/tweets-eth_classic#16]
This issue is now being used to gather plans for Rules for acceptable and unacceptable tweet contents.

It replaces https://github.com/ethereumclassic/tweets-eth_classic/issues/18.

**Comment by brolal** [comment]
Not sure we need rules if we push the number of approvals to 5-6.
If we do a spin first, we can find out what is good or bad, and decide for a rule imo
Other then that, the path is clear: get handler verified as an organization
https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts#creators

**Comment by w1g0** [comment]
>Not sure we need rules if we push the number of approvals to 5-6.

I'm sure we need rules!

**Comment by brolal** [comment]
Common sense may beat whatever rules we draft, but sure, go ahead.

**Comment by IstoraMandiri** [comment]
Moved to #18
