### ISSUE TITLE
Rules to Prevent Approvers from  Ninja-Tweeting

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/tweets-eth_classic#17]
When a proposal gets a review all other reviewers can review and edit the Tweet afterwards and broadcast anything they want?
If the file gets edited I would like to see a reset and the need for a new review quota.

**Comment by IstoraMandiri** [comment]
Good point, we'll need to figure out how to do this in github.

I think we need to be doing it be highlighting specific lines in the tweet when making review approvals.

**Comment by IstoraMandiri** [comment]
I have fixed this

![image](https://user-images.githubusercontent.com/1696942/196016357-770b06c9-df84-4c4b-9f4b-9f853aae54b7.png)
