### ISSUE TITLE
Draft rules for tweet contents

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/tweets-eth_classic#18]
Let's use this thread to propose ideas for rules that will be collated later into a checklist that moderators can use to approve or reject tweet proposals.

Once we have a strict canonical set, which will be used for `eth_classic`, we can then create another set of modifications for `ETC_Network`, which can be looser.

---

I'll start 

There should be limits on what kind of tweets are published

- No spam
- No scams
- No drama
- Stay classy

Anything else?

**Comment by IstoraMandiri** [comment]
Comments from @brolal in the other thread

Not sure we need rules if we push the number of approvals to 5-6.
If we do a spin first, we can find out what is good or bad, and decide for a rule imo
Other then that, the path is clear: get handler verified as an organization
https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts#creators

**Comment by TheCrowbill** [comment]
In an effort to create a meaningful distinction between the two TT accounts as well as to address some of the concerns about objectivity in content, I propose that all tweets from the `eth_classic` handle should be written from the point of view of the ETC blockchain itself. The `ETC_network` handle can then be used more loosely for such things as retweets of others' comments about ETC or community news, etc. 

If a proposed tweet can't pass a test of "If it had a voice, would the chain itself say...." then that tweet would not be acceptable from the `eth_classic` handle. This test should greatly reduce issues about whether tweeted content appears to be biased when the subject is a topic on which the community has not reached a clear consensus.

**Comment by IstoraMandiri** [comment]
Styling guides

-  Use double spaced new lines
- Use hashtags
- Emojis!

**Comment by w1g0** [comment]
Do we like a Hashtag footer?
a minimum advised set of tags...
I like #EthereumClassic when it's about content,
$ETC when it's about price action for example.

**Comment by Tweaker177** [comment]
> 

We should include both IMO as many people use tools that count daily, weekly, monthly useage of #EthereumClassic and $ETC as indicators of market sentiment as well as overall activity on chain.  It’s why I try to tweet with them included as much as possible, so it adds to the number, along with re-tweets.

**Comment by w1g0** [comment]
> We should include both IMO as many people use tools that count daily, weekly, monthly useage of #EthereumClassic and $ETC as indicators of market sentiment as well as overall activity on chain. It’s why I try to tweet with them included as much as possible, so it adds to the number, along with re-tweets.

Sounds good to me 👍

**Comment by IstoraMandiri** [comment]
I think we should add a rule about not having naked retweets (with no text).

- If we add text to the tweet we can add context and hashtags
- No-text retweets do not create shareable links
- When other people retweet the our naked retweet it will not credit our account

**Comment by IstoraMandiri** [comment]
Please move further discussion to #32
